[rospy.client][INFO] 2025-06-30 19:57:45,546: init_node, name[/turtlebot_teleop_keyboard], pid[21627]
[xmlrpc][INFO] 2025-06-30 19:57:45,547: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2025-06-30 19:57:45,547: Started XML-RPC server [http://192.168.1.124:43313/]
[rospy.impl.masterslave][INFO] 2025-06-30 19:57:45,547: _ready: http://192.168.1.124:43313/
[rospy.registration][INFO] 2025-06-30 19:57:45,548: Registering with master node http://localhost:11311
[rospy.init][INFO] 2025-06-30 19:57:45,548: ROS Slave URI: [http://192.168.1.124:43313/]
[rospy.init][INFO] 2025-06-30 19:57:45,548: registered with master
[xmlrpc][INFO] 2025-06-30 19:57:45,548: xml rpc node: starting XML-RPC server
[rospy.rosout][INFO] 2025-06-30 19:57:45,548: initializing /rosout core topic
[rospy.rosout][INFO] 2025-06-30 19:57:45,551: connected to core topic /rosout
[rospy.simtime][INFO] 2025-06-30 19:57:45,552: initializing /clock core topic
[rospy.simtime][INFO] 2025-06-30 19:57:45,553: connected to core topic /clock
[rospy.internal][INFO] 2025-06-30 19:57:45,554: topic[/clock] adding connection to [http://192.168.1.124:34153/], count 0
[rospy.internal][INFO] 2025-06-30 19:57:45,755: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2025-06-30 19:57:45,851: topic[/cmd_vel_mux/input/teleop] adding connection to [/mobile_base_nodelet_manager], count 0
[rospy.internal][INFO] 2025-06-30 20:07:29,897: topic[/cmd_vel_mux/input/teleop] removing connection to /mobile_base_nodelet_manager
[rospy.internal][ERROR] 2025-06-30 20:07:29,920: Unable to initiate TCP/IP socket to 192.168.1.124:59467 (http://192.168.1.124:34153/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 594, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 59467 to [192.168.1.124:49612 on socket 18]] [/turtlebot_teleop_keyboard].

[rospy.internal][ERROR] 2025-06-30 20:07:30,921: Unable to initiate TCP/IP socket to 192.168.1.124:59467 (http://192.168.1.124:34153/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 594, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 59467 to [192.168.1.124:49754 on socket 17]] [/turtlebot_teleop_keyboard].

[rospy.core][INFO] 2025-06-30 20:07:31,248: signal_shutdown [atexit]
[rospy.internal][INFO] 2025-06-30 20:07:31,252: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2025-06-30 20:07:31,252: topic[/clock] removing connection to http://192.168.1.124:34153/
[rospy.impl.masterslave][INFO] 2025-06-30 20:07:31,252: atexit
