[rospy.client][INFO] 2017-07-09 21:52:36,482: init_node, name[/target_spawner], pid[17938]
[xmlrpc][INFO] 2017-07-09 21:52:36,482: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-07-09 21:52:36,482: Started XML-RPC server [http://udacity:46049/]
[rospy.impl.masterslave][INFO] 2017-07-09 21:52:36,483: _ready: http://udacity:46049/
[rospy.init][INFO] 2017-07-09 21:52:36,483: ROS Slave URI: [http://udacity:46049/]
[xmlrpc][INFO] 2017-07-09 21:52:36,483: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-07-09 21:52:36,484: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-07-09 21:52:36,584: registered with master
[rospy.rosout][INFO] 2017-07-09 21:52:36,584: initializing /rosout core topic
[rospy.rosout][INFO] 2017-07-09 21:52:36,591: connected to core topic /rosout
[rospy.simtime][INFO] 2017-07-09 21:52:36,600: initializing /clock core topic
[rospy.simtime][INFO] 2017-07-09 21:52:36,670: connected to core topic /clock
[rosout][INFO] 2017-07-09 21:52:36,694: Loading model XML from ros parameter
[rosout][INFO] 2017-07-09 21:52:36,708: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2017-07-09 21:52:36,793: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-07-09 21:52:37,621: topic[/clock] adding connection to [http://udacity:38105/], count 0
[rosout][INFO] 2017-07-09 21:52:37,624: Calling service /gazebo/spawn_urdf_model
[rosout][INFO] 2017-07-09 21:52:37,755: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2017-07-09 21:52:37,756: signal_shutdown [atexit]
[rospy.internal][INFO] 2017-07-09 21:52:37,758: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-07-09 21:52:37,759: topic[/clock] removing connection to http://udacity:38105/
[rospy.internal][WARNING] 2017-07-09 21:52:37,760: Unknown error initiating TCP/IP socket to udacity:39573 (http://udacity:38105/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-07-09 21:52:37,760: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2017-07-09 21:52:37,760: atexit
